### ISSUE TITLE
Нет статей в поддержку действий РКН

### ISSUE THREAD

**Issue by sobolevn** [nazarov-tech/rkn#1]
В списке есть "против" и "сдержанно/косвенно".

Судя по пункту:
> Держитесь нейтральности и объективности

необходимо добавить раздел с позицией, которая поддерживает действия РКН.

**Comment by bruno-gelb** [comment]
согласен, выглядит как несоответствие ) Подумаю как лучше поправить

**Comment by bruno-gelb** [comment]
закрыл в https://github.com/nazarov-tech/rkn/commit/aa1cad8659f6a87cecb8ca5de1b9e4ca18df6e19

позднее ещё думаю добавляю объяснение, какой цели служит список (иллюстрировать массовость реакции), чтобы было совсем ок.
